services:

  # ─── Application services ──────────────────────────────────────────────────

  vote:
    build:
      context: ./vote
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8080:80"
    networks:
      - front-tier
      - back-tier

  result:
    build:
      context: ./result
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:80"
    networks:
      - front-tier
      - back-tier

  worker:
    build:
      context: ./worker
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - back-tier

  # ─── Infrastructure ────────────────────────────────────────────────────────

  redis:
    image: redis:alpine
    volumes:
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/redis.sh
      interval: "5s"
    networks:
      - back-tier

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "5s"
    networks:
      - back-tier

  waf-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "super_secret_password_here"
      POSTGRES_DB: "waf_logs"
    volumes:
      - "waf-db-data:/var/lib/postgresql/data"
      # This mounts our schema into the exact folder Postgres checks on first boot
      - "./gateway/schema.sql:/docker-entrypoint-initdb.d/schema.sql"
    networks:
      - front-tier

  waf-redis:
    image: redis:alpine
    networks:
      - front-tier

  gateway:
    build: ./gateway/
    ports:
      - "9090:9090"
    depends_on:
      - vote
      - waf-db
      - waf-redis
    networks:
      - front-tier


volumes:
  db-data:
  grafana-data:
  waf-db-data:

networks:
  front-tier:
  back-tier:
