apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: waf-redis
  labels:
    app: waf-redis
spec:
  serviceName: "waf-redis"
  replicas: 1
  selector:
    matchLabels:
      app: waf-redis
  template:
    metadata:
      labels:
        app: waf-redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        command: ["redis-server", "--appendonly", "yes"]
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: waf-redis-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: waf-redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: waf-redis
  labels:
    app: waf-redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: waf-redis
